version: 0.2

phases:
  install:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  pre_build:
    commands:
      - terraform init
      - echo Hello Srini!!!12
      - terraform validate -no-color
  build:
    commands:
      - terraform plan
  deploy:
    commands:
      - terraform apply
artifacts:
  files:
    - "**/*"
  discard-paths: yes
